"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["Peramesa.py"]
DATA_FILES = [
    "pera.icns",
    "peramesa.png",
    "help_text.txt",
    "help_text_en.txt",
]
OPTIONS = {
    "iconfile": "pera.icns",
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
